# Generated by Django 2.2.1 on 2019-05-23 04:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('pincode', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('pancard', models.CharField(max_length=40)),
                ('adhaar', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('residence_type', models.CharField(choices=[('rented', 'rented'), ('alloted', 'alloted'), ('owned', 'owned'), ('parental', 'parental')], max_length=10)),
                ('living_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('address', models.TextField(max_length=400)),
                ('street_landmark', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=4, max_digits=15)),
                ('employment_type', models.CharField(choices=[('Salaried', 'Salaried'), ('SEP', 'Self Employed Professional'), ('SENP', 'self employed non professional')], max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('current_job_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('job_stability', models.IntegerField()),
                ('loan_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('surgery', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=100)),
                ('hospital_location', models.TextField(max_length=500)),
                ('loan_rate', models.DecimalField(decimal_places=4, max_digits=15)),
                ('loan_tenure', models.IntegerField()),
                ('account_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=100)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Data')),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/')),
                ('patient_document', models.CharField(choices=[('bank_statement', 'bank_statement'), ('pancard', 'pancard'), ('photo', 'photo'), ('itr', 'itr'), ('salaary_slip', 'salary_slip'), ('adhaar', 'adhaar'), ('driving_licence', 'driving_licence'), ('passport', 'passport'), ('allotment_letter', 'allotment_letter'), ('rent_agreement', 'rent_agreement'), ('electricity_bill', 'electricity_bill'), ('mediccal_bill', 'medical_bill'), ('discharge_report', 'discharge_report'), ('voter_id', 'voter_id'), ('current_address_proof', 'current_address_proof'), ('gas_bill', 'gas_bill'), ('landline_bill', 'landline_bill'), ('property_papers', 'property_papers'), ('water_bill', 'water_bill'), ('house_tax', 'house_tax'), ('adhaarback', 'adhaarback'), ('others', 'others')], max_length=30)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Data')),
            ],
        ),
    ]
